[target.x86_64-pc-windows-msvc]
rustflags = ["-L", "C:\\Users\\1\\OneDrive\\Bureau\\DeepDive\\DeepSide\\extras\\npcap-sdk\\Lib\\x64"]

[env]
PCAP_LIB_DIR = "C:\\Users\\1\\OneDrive\\Bureau\\DeepDive\\DeepSide\\extras\\npcap-sdk\\Lib\\x64"
